# Generated by Django 6.0.3 on 2026-04-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_deployment_from_cadre_category_deployment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='onboarding_status',
            field=models.CharField(choices=[('not_set', 'Not Set'), ('parenting', 'Parenting'), ('redesignation', 'Redesignation')], default='not_set', max_length=20),
        ),
    ]
