# Generated by Django 6.0.3 on 2026-04-26 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_add_onboarding_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bio_verification_note',
            field=models.TextField(blank=True, verbose_name='Bio Rejection Reason'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bio_verification_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('returned', 'Returned to Employee')], default='pending', max_length=20, verbose_name='Bio Data Verification'),
        ),
        migrations.AddField(
            model_name='employee',
            name='cert_verification_note',
            field=models.TextField(blank=True, verbose_name='Certifications Rejection Reason'),
        ),
        migrations.AddField(
            model_name='employee',
            name='cert_verification_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('returned', 'Returned to Employee')], default='pending', max_length=20, verbose_name='Certifications Verification'),
        ),
        migrations.AddField(
            model_name='employee',
            name='overall_verification_note',
            field=models.TextField(blank=True, verbose_name='Overall Rejection Reason'),
        ),
        migrations.AddField(
            model_name='employee',
            name='overall_verification_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('returned', 'Returned to Employee')], default='pending', max_length=20, verbose_name='Overall Profile Verification'),
        ),
        migrations.AddField(
            model_name='employee',
            name='pub_events_verification_note',
            field=models.TextField(blank=True, verbose_name='Publications & Events Rejection Reason'),
        ),
        migrations.AddField(
            model_name='employee',
            name='pub_events_verification_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('returned', 'Returned to Employee')], default='pending', max_length=20, verbose_name='Publications & Events Verification'),
        ),
        migrations.AddField(
            model_name='employee',
            name='qual_verification_note',
            field=models.TextField(blank=True, verbose_name='Qualifications Rejection Reason'),
        ),
        migrations.AddField(
            model_name='employee',
            name='qual_verification_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('returned', 'Returned to Employee')], default='pending', max_length=20, verbose_name='Qualifications Verification'),
        ),
        migrations.AddField(
            model_name='employee',
            name='verification_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='verification_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_done', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_verification_note',
            field=models.TextField(blank=True, verbose_name='Work Rejection Reason'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_verification_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('returned', 'Returned to Employee')], default='pending', max_length=20, verbose_name='Work Info Verification'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='onboarding_status',
            field=models.CharField(choices=[('not_set', 'Not Set'), ('parenting', 'Parenting'), ('redesignation', 'Redesignation'), ('both', 'Both')], default='not_set', max_length=20),
        ),
    ]
