# Generated by Django 6.0.3 on 2026-04-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_add_parenting_status_and_verification_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='onboarding_status',
            field=models.CharField(choices=[('not_set', 'Not Set'), ('parenting', 'Parented'), ('redesignation', 'Redesignation'), ('both', 'Both')], default='not_set', max_length=20),
        ),
    ]
