# Generated by Django 6.0.3 on 2026-03-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='allow_employees_view_directory',
            field=models.BooleanField(default=False),
        ),
    ]
